// Generates the gig-radar site files from gig-data.json (the source of truth):
//   - gig-data.js   (window.GIG_DATA = ... for file:// use by gigs.html)
//   - gigs.ics      (subscribable feed of upcoming in-genre gigs)
// It only ADDS derived fields (dateLabel, weekday, monthKey, sortKey, travel,
// genresLabel, isPast); it never rewrites the curated content.

import fs from "node:fs";

const root = new URL("..", import.meta.url);
const srcPath = new URL("gig-data.json", root);
const outJsPath = new URL("gig-data.js", root);
const outIcsPath = new URL("gigs.ics", root);

const today = new Intl.DateTimeFormat("en-CA", {
  timeZone: "Europe/London",
  year: "numeric",
  month: "2-digit",
  day: "2-digit"
}).format(new Date());

const data = JSON.parse(fs.readFileSync(srcPath, "utf8"));

const WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
];

// Rough proximity bucketing so the page can group by "how far from Surbiton".
const LOCAL = /surbiton|berrylands|tolworth|kingston|long ditton|thames ditton|surrey|new malden|wimbledon|richmond|twickenham|barnes|putney|kew|teddington|hampton|molesey|esher|brentford|mortlake|sheen/i;
const CENTRAL = /london|soho|camden|battersea|kennington|islington|hackney|shoreditch|clerkenwell|holborn|waterloo|southbank|south bank|brixton|dalston|peckham|greenwich|leytonstone|walthamstow|carnaby|mayfair|westminster|city/i;

function travelBucket(area = "") {
  if (LOCAL.test(area)) return "Local (SW London)";
  if (CENTRAL.test(area)) return "Central London";
  return "Day-trip";
}

function enrich(gig) {
  const [y, m, d] = String(gig.date).split("-").map(Number);
  // Construct as UTC noon to avoid any timezone date-shift.
  const dt = new Date(Date.UTC(y, (m || 1) - 1, d || 1, 12));
  const weekday = WEEKDAYS[dt.getUTCDay()];
  const dateLabel = `${weekday} ${d} ${MONTHS[(m || 1) - 1]}`;
  const monthKey = `${y}-${String(m).padStart(2, "0")}`;
  const monthLabel = `${MONTHS[(m || 1) - 1]} ${y}`;
  const time = gig.time || "";
  const sortKey = `${gig.date} ${time || "99:99"}`;
  const genres = Array.isArray(gig.genres) ? gig.genres : [];
  const end = gig.endDate || gig.date;
  return {
    ...gig,
    weekday,
    dateLabel,
    monthKey,
    monthLabel,
    sortKey,
    travel: gig.travel || travelBucket(gig.area),
    genresLabel: genres.join(" · "),
    isPast: end < today,
    isMultiDay: Boolean(gig.endDate && gig.endDate !== gig.date)
  };
}

const gigs = (data.gigs || [])
  .map(enrich)
  .sort((a, b) => a.sortKey.localeCompare(b.sortKey));

const upcoming = gigs.filter((g) => !g.isPast);

const allGenres = [...new Set(gigs.flatMap((g) => g.genres || []))].sort();
const allAreas = [...new Set(gigs.map((g) => g.travel))];

const out = {
  meta: {
    ...(data.meta || {}),
    generated: new Date().toISOString(),
    dateBasis: today,
    counts: {
      total: gigs.length,
      upcoming: upcoming.length,
      watchlist: (data.watchlist || []).length
    },
    genres: allGenres,
    travelBuckets: allAreas
  },
  gigs,
  watchlist: data.watchlist || []
};

fs.writeFileSync(
  outJsPath,
  `// AUTO-GENERATED by updater/generate-gigs.mjs — do not edit by hand.\n` +
    `window.GIG_DATA = ${JSON.stringify(out, null, 2)};\n`,
  "utf8"
);

// ---- ICS feed (upcoming only; floating local time) ----
function icsEscape(s = "") {
  return String(s).replace(/[\\;,]/g, (c) => "\\" + c).replace(/\n/g, "\\n");
}
function stamp(dateStr, timeStr) {
  const date = String(dateStr).replace(/-/g, "");
  if (timeStr && /^\d{1,2}:\d{2}$/.test(timeStr)) {
    const [hh, mm] = timeStr.split(":");
    return `${date}T${hh.padStart(2, "0")}${mm}00`;
  }
  return date; // all-day
}
const lines = [
  "BEGIN:VCALENDAR",
  "VERSION:2.0",
  "PRODID:-//local-events//gig-radar//EN",
  "CALSCALE:GREGORIAN",
  "METHOD:PUBLISH",
  `X-WR-CALNAME:${icsEscape(out.meta.title || "Gig Radar")}`,
  "X-WR-TIMEZONE:Europe/London"
];
for (const g of upcoming) {
  const dtStart = stamp(g.date, g.time);
  const allDay = !/\T/.test(dtStart);
  const endBase = g.endDate || g.date;
  lines.push("BEGIN:VEVENT");
  lines.push(`UID:${g.id}@local-events-gig-radar`);
  lines.push(`DTSTAMP:${today.replace(/-/g, "")}T000000Z`);
  if (allDay) {
    // For all-day, DTEND is exclusive -> next day after endBase.
    const [ey, em, ed] = endBase.split("-").map(Number);
    const endEx = new Date(Date.UTC(ey, em - 1, ed + 1, 12));
    const endExStr = `${endEx.getUTCFullYear()}${String(endEx.getUTCMonth() + 1).padStart(2, "0")}${String(endEx.getUTCDate()).padStart(2, "0")}`;
    lines.push(`DTSTART;VALUE=DATE:${dtStart}`);
    lines.push(`DTEND;VALUE=DATE:${endExStr}`);
  } else {
    lines.push(`DTSTART:${dtStart}`);
  }
  const title = `${g.artist ? g.artist + " — " : ""}${g.title || g.artist || "Gig"}`;
  lines.push(`SUMMARY:${icsEscape(title)}`);
  const locParts = [g.venue, g.area].filter(Boolean).join(", ");
  if (locParts) lines.push(`LOCATION:${icsEscape(locParts)}`);
  const desc = [
    g.genresLabel && `Genres: ${g.genresLabel}`,
    g.cost && `Cost: ${g.cost}`,
    g.note,
    g.url
  ].filter(Boolean).join("\n");
  if (desc) lines.push(`DESCRIPTION:${icsEscape(desc)}`);
  if (g.url) lines.push(`URL:${g.url}`);
  lines.push("END:VEVENT");
}
lines.push("END:VCALENDAR");
fs.writeFileSync(outIcsPath, lines.join("\r\n") + "\r\n", "utf8");

console.log(
  `gig-radar generated: ${gigs.length} gigs (${upcoming.length} upcoming), ` +
    `${(data.watchlist || []).length} watchlist, ${allGenres.length} genres.`
);
